# Generated by Django 5.2.2 on 2025-06-25 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_turma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('carga_horaria', models.PositiveIntegerField()),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='core.professor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='core.turma')),
            ],
        ),
    ]
