# Generated by Django 5.2.2 on 2025-06-24 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_turma'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='especialidade',
            new_name='formacao',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='telefone',
        ),
        migrations.AddField(
            model_name='professor',
            name='area_atuacao',
            field=models.CharField(default='Indefinido', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='cpf',
            field=models.CharField(default='indefinido', max_length=14, unique=True),
            preserve_default=False,
        ),
    ]
