# Generated by Django 5.2.2 on 2025-06-25 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_disciplina'),
        ('core', '0004_rename_especialidade_professor_formacao_and_more'),
    ]

    operations = [
    ]
