# Generated by Django 5.2.2 on 2025-06-25 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_frequencia_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequencia',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='core.disciplina'),
        ),
    ]
