# Generated by Django 5.2.2 on 2025-06-25 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_frequencia_nota'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrinhoMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrinhos', to='core.aluno')),
            ],
        ),
    ]
